# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPTGUI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='data',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='unique_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
