# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPTGUI', '0002_auto_20170130_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='preanalysis_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='upload_status',
            field=models.BooleanField(default=False),
        ),
    ]
