# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPTGUI', '0004_auto_20170213_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='preanalysis_token',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='preanalysis_status',
            field=models.CharField(choices=[('error', 'An unknown error occurred'), ('na', 'Not available'), ('error', 'An error occured'), ('queued', 'Sent to the processing queue'), ('inprogress', 'Preprocessing in progress'), ('fileformaterror', 'Unrecognized file format'), ('ok', 'Preprocessing completed with success')], default='na', max_length=100),
        ),
    ]
