# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPTGUI', '0009_dataset_jld'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='pre_mean_jump_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pre_mean_length_of_trajectories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pre_mean_particles_per_frame',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pre_median_jump_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pre_median_length_of_trajectories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pre_median_particles_per_frame',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pre_njumps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pre_ntraces3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
