# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPTGUI', '0011_dataset_pre_nframes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.FileField(blank=True, null=True, upload_to='downloads/')),
                ('export_svg', models.FileField(blank=True, null=True, upload_to='downloads/')),
                ('export_eps', models.FileField(blank=True, null=True, upload_to='downloads/')),
                ('export_png', models.FileField(blank=True, null=True, upload_to='downloads/')),
                ('export_zip', models.FileField(blank=True, null=True, upload_to='downloads/')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPTGUI.Dataset')),
            ],
        ),
    ]
