# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPTGUI', '0013_auto_20170411_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='export_pdf',
            field=models.FileField(blank=True, null=True, upload_to='downloads/'),
        ),
        migrations.AddField(
            model_name='download',
            name='status_pdf',
            field=models.CharField(choices=[('error', 'An unknown error occurred'), ('na', 'Not available'), ('error', 'An error occured'), ('queued', 'Sent to the processing queue'), ('uploaded', 'Uploaded done'), ('inprogress', 'Preprocessing in progress'), ('fileformaterror', 'Unrecognized file format'), ('ok', 'Preprocessing completed with success')], default='na', max_length=100),
        ),
    ]
