# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPTGUI', '0014_auto_20170411_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to='SPTGUI/static/SPTGUI/downloads'),
        ),
        migrations.AlterField(
            model_name='download',
            name='export_eps',
            field=models.FileField(blank=True, null=True, upload_to='SPTGUI/static/SPTGUI/downloads'),
        ),
        migrations.AlterField(
            model_name='download',
            name='export_pdf',
            field=models.FileField(blank=True, null=True, upload_to='SPTGUI/static/SPTGUI/downloads'),
        ),
        migrations.AlterField(
            model_name='download',
            name='export_png',
            field=models.FileField(blank=True, null=True, upload_to='SPTGUI/static/SPTGUI/downloads'),
        ),
        migrations.AlterField(
            model_name='download',
            name='export_svg',
            field=models.FileField(blank=True, null=True, upload_to='SPTGUI/static/SPTGUI/downloads'),
        ),
        migrations.AlterField(
            model_name='download',
            name='export_zip',
            field=models.FileField(blank=True, null=True, upload_to='SPTGUI/static/SPTGUI/downloads'),
        ),
        migrations.AlterField(
            model_name='download',
            name='params',
            field=models.FileField(blank=True, null=True, upload_to='SPTGUI/static/SPTGUI/downloads'),
        ),
    ]
