# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPTGUI', '0016_auto_20170417_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
