# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPTGUI', '0018_auto_20170516_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=1000)),
                ('validated', models.BooleanField(default=False)),
                ('token', models.CharField(default='', max_length=256)),
                ('add_date', models.DateTimeField(verbose_name='date created')),
                ('validation_date', models.DateTimeField(verbose_name='date validated')),
            ],
        ),
    ]
