# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPTGUI', '0024_dataset_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUploadAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='na', max_length=100)),
                ('expectedSHA', models.CharField(default='na', max_length=100)),
                ('fileReceived', models.BooleanField(default=False)),
                ('fmt', models.CharField(default='na', max_length=100)),
                ('version', models.CharField(default='na', max_length=100)),
                ('url_basename', models.CharField(default='na', max_length=100)),
                ('creation_date', models.DateTimeField(blank=True, null=True, verbose_name='date created')),
            ],
        ),
    ]
